SRC =  main.cpp Harl.cpp
CPPFLAGS = -Wall -Wextra -Werror -std=c++98
CC = c++ 
NAME =  Harl2.0

all : $(NAME)
$(NAME) : $(SRC)		
		$(CC) $(CPPFLAGS) $(SRC) -o $(NAME)

clean :

fclean :
	rm -rf $(NAME)
re : fclean all