SRC = convert.cpp
CPPFLAGS = -Wall -Wextra -Werror -std=c++98
CC = c++
NAME = convert

all : $(NAME)
$(NAME) : $(SRC)		
		$(CC) $(CPPFLAGS) $(SRC) -o $(NAME)

clean :
	rm -rf $(NAME)
fcleen : 
		rm -rf $(NAME)
re : fcleen all
