SRC = main.cpp
NAME = Easyfind
CPPFLAGS = -Wall -Wextra -Werror -std=c++98
CC = c++

all : $(NAME)
$(NAME) : $(SRC)		
		$(CC) $(CPPFLAGS) $(SRC) -o $(NAME) 

cleen :

fcleen : 
		rm -rf $(NAME)
re : fcleen all