SRC = Zombie.cpp newZombie.cpp randomChump.cpp  main.cpp
CPPFLAGS = -Wall -Wextra -Werror -std=c++98
CC = c++ 
NAME =  BraiiiiiiinnnzzzZ

all : $(NAME)
$(NAME) : $(SRC)		
		$(CC) $(CPPFLAGS) $(SRC) -o $(NAME)

clean :

fclean :
	rm -rf $(NAME)
re : fclean all